In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df=pd.read_csv("iphone 15 review dataset.csv")
df

Product Name      Price         ROM  \
0             Apple iPhone 15 (Blue, 128 GB)    ₹64,900  128 GB ROM   
1             Apple iPhone 15 (Blue, 128 GB)    ₹64,900  128 GB ROM   
2             Apple iPhone 15 (Blue, 128 GB)    ₹64,900  128 GB ROM   
3             Apple iPhone 15 (Blue, 128 GB)    ₹64,900  128 GB ROM   
4             Apple iPhone 15 (Blue, 128 GB)    ₹64,900  128 GB ROM   
...                                      ...        ...         ...   
23755  Apple iPhone 15 Plus (Yellow, 512 GB)  ₹1,04,900  512 GB ROM   
23756  Apple iPhone 15 Plus (Yellow, 512 GB)  ₹1,04,900  512 GB ROM   
23757  Apple iPhone 15 Plus (Yellow, 512 GB)  ₹1,04,900  512 GB ROM   
23758  Apple iPhone 15 Plus (Yellow, 512 GB)  ₹1,04,900  512 GB ROM   
23759  Apple iPhone 15 Plus (Yellow, 512 GB)  ₹1,04,900  512 GB ROM   

                                            Display  \
0      15.49 cm (6.1 inch) Super Retina XDR Display   
1      15.49 cm (6.1 inch) Super Retina XDR Display   
2      15.49 cm (6.1 inch) Super Retina XDR Display   
3      15.49 cm (6.1 inch) Super Retina XDR Display   
4      15.49 cm (6.1 inch) Super Retina XDR Display   
...                                             ...   
23755  17.02 cm (6.7 inch) Super Retina XDR Display   
23756  17.02 cm (6.7 inch) Super Retina XDR Display   
23757  17.02 cm (6.7 inch) Super Retina XDR Display   
23758  17.02 cm (6.7 inch) Super Retina XDR Display   
23759  17.02 cm (6.7 inch) Super Retina XDR Display   

                                Camera  \
0      48MP + 12MP | 12MP Front Camera   
1      48MP + 12MP | 12MP Front Camera   
2      48MP + 12MP | 12MP Front Camera   
3      48MP + 12MP | 12MP Front Camera   
4      48MP + 12MP | 12MP Front Camera   
...                                ...   
23755  48MP + 12MP | 12MP Front Camera   
23756  48MP + 12MP | 12MP Front Camera   
23757  48MP + 12MP | 12MP Front Camera   
23758  48MP + 12MP | 12MP Front Camera   
23759  48MP + 12MP | 12MP Front Camera   

                                         Processor  \
0      A16 Bionic Chip, 6 Core Processor Processor   
1      A16 Bionic Chip, 6 Core Processor Processor   
2      A16 Bionic Chip, 6 Core Processor Processor   
3      A16 Bionic Chip, 6 Core Processor Processor   
4      A16 Bionic Chip, 6 Core Processor Processor   
...                                            ...   
23755  A16 Bionic Chip, 6 Core Processor Processor   
23756  A16 Bionic Chip, 6 Core Processor Processor   
23757  A16 Bionic Chip, 6 Core Processor Processor   
23758  A16 Bionic Chip, 6 Core Processor Processor   
23759  A16 Bionic Chip, 6 Core Processor Processor   

                                                Warranty  Rating  \
0      1 year warranty for phone and 1 year warranty ...     5.0   
1      1 year warranty for phone and 1 year warranty ...     5.0   
2      1 year warranty for phone and 1 year warranty ...     5.0   
3      1 year warranty for phone and 1 year warranty ...     4.0   
4      1 year warranty for phone and 1 year warranty ...     5.0   
...                                                  ...     ...   
23755  1 year warranty for phone and 1 year warranty ...     5.0   
23756  1 year warranty for phone and 1 year warranty ...     5.0   
23757  1 year warranty for phone and 1 year warranty ...     5.0   
23758  1 year warranty for phone and 1 year warranty ...     5.0   
23759  1 year warranty for phone and 1 year warranty ...     NaN   

                Review Title  \
0          Worth every penny   
1                  Just wow!   
2      Mind-blowing purchase   
3                Good choice   
4                  Just wow!   
...                      ...   
23755                Awesome   
23756                Awesome   
23757              Fabulous!   
23758              Fabulous!   
23759  Slightly disappointed   

                                             Review Text  
0      Just go for it.Amazing one.Beautiful camera wi...  
1                                  Awesome 🔥

In [3]:
df.isnull().any()

Product Name    False
Price           False
ROM             False
Display         False
Camera          False
Processor       False
Warranty        False
Rating           True
Review Title    False
Review Text     False
dtype: bool

handling missing value

In [4]:
df = df.dropna(subset=['Rating'])

In [5]:
df.isnull().any()

Product Name    False
Price           False
ROM             False
Display         False
Camera          False
Processor       False
Warranty        False
Rating          False
Review Title    False
Review Text     False
dtype: bool

Check If There Are Any Duplicates

In [8]:
has_duplicates = df.duplicated().any()
print(has_duplicates)

True


In [9]:
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

Number of duplicate rows: 639


In [10]:
df.drop_duplicates(inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [11]:
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

Number of duplicate rows: 0


Drop Unnecessary Columns/Rows

In [12]:
df["Processor"].value_counts()

Processor
A16 Bionic Chip, 6 Core Processor Processor    22800
Name: count, dtype: int64

In [13]:
df["Warranty"].value_counts()

Warranty
1 year warranty for phone and 1 year warranty for in Box Accessories.    22800
Name: count, dtype: int64

In [14]:
df.drop(columns=['Warranty', 'Processor'], inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\3934200690.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Warranty', 'Processor'], inplace=True)


In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22800 entries, 0 to 23758
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Product Name  22800 non-null  object 
 1   Price         22800 non-null  object 
 2   ROM           22800 non-null  object 
 3   Display       22800 non-null  object 
 4   Camera        22800 non-null  object 
 5   Rating        22800 non-null  float64
 6   Review Title  22800 non-null  object 
 7   Review Text   22800 non-null  object 
dtypes: float64(1), object(7)
memory usage: 1.6+ MB


Feature Engineering

In [ ]:
# Clean 'Price' by removing ₹ 
df['Price'] = df['Price'].replace('[₹,]', '', regex=True).astype(float)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\2234087208.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df['Price'].replace('[₹,]', '', regex=True).astype(float)


In [17]:
df['ROM_GB'] = df['ROM'].str.extract(r'(\d+)').astype(float)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\269444451.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROM_GB'] = df['ROM'].str.extract(r'(\d+)').astype(float)


In [18]:
df['Display_Size_inch'] = df['Display'].str.extract(r'(\d+\.?\d*)').astype(float)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\142511541.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Display_Size_inch'] = df['Display'].str.extract(r'(\d+\.?\d*)').astype(float)


In [19]:
df['Main_Camera_MP'] = df['Camera'].str.extract(r'(\d+)(?=MP)').astype(float)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\869229981.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Main_Camera_MP'] = df['Camera'].str.extract(r'(\d+)(?=MP)').astype(float)


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22800 entries, 0 to 23758
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Product Name       22800 non-null  object 
 1   Price              22800 non-null  float64
 2   ROM                22800 non-null  object 
 3   Display            22800 non-null  object 
 4   Camera             22800 non-null  object 
 5   Rating             22800 non-null  float64
 6   Review Title       22800 non-null  object 
 7   Review Text        22800 non-null  object 
 8   ROM_GB             22800 non-null  float64
 9   Display_Size_inch  22800 non-null  float64
 10  Main_Camera_MP     22800 non-null  float64
dtypes: float64(5), object(6)
memory usage: 2.1+ MB


In [21]:
df.drop(columns=['ROM', 'Display','Camera'], inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16840\1089565473.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['ROM', 'Display','Camera'], inplace=True)


In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22800 entries, 0 to 23758
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Product Name       22800 non-null  object 
 1   Price              22800 non-null  float64
 2   Rating             22800 non-null  float64
 3   Review Title       22800 non-null  object 
 4   Review Text        22800 non-null  object 
 5   ROM_GB             22800 non-null  float64
 6   Display_Size_inch  22800 non-null  float64
 7   Main_Camera_MP     22800 non-null  float64
dtypes: float64(5), object(3)
memory usage: 1.6+ MB


In [23]:
df

Product Name     Price  Rating  \
0             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
1             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
2             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
3             Apple iPhone 15 (Blue, 128 GB)   64900.0     4.0   
4             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
...                                      ...       ...     ...   
23754  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     3.0   
23755  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
23756  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
23757  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
23758  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   

                Review Title  \
0          Worth every penny   
1                  Just wow!   
2      Mind-blowing purchase   
3                Good choice   
4                  Just wow!   
...                      ...   
23754                   Nice   
23755                Awesome   
23756                Awesome   
23757              Fabulous!   
23758              Fabulous!   

                                             Review Text  ROM_GB  \
0      Just go for it.Amazing one.Beautiful camera wi...   128.0   
1                                  Awesome 🔥🔥☺️READ MORE   128.0   
2                          High quality camera😍READ MORE   128.0   
3                                     Very niceREAD MORE   128.0   
4          Camera Quality Is Improved Loving ItREAD MORE   128.0   
...                                                  ...     ...   
23754  Its camera is too weak. I found it has a refle...   512.0   
23755                              Good productREAD MORE   512.0   
23756  Value for money, Awesome camera, everything is...   512.0   
23757                              Best Phone 📱READ MORE   512.0   
23758  I am using iPhone 15 plus for last 50 days.Sha...   512.0   

       Display_Size_inch  Main_Camera_MP  
0                  15.49            48.0  
1                  15.49            48.0  
2                  15.49            48.0  
3                  15.49            48.0  
4                  15.49            48.0  
...                  ...             ...  
23754              17.02            48.0  
23755              17.02            48.0  
23756              17.02            48.0  
23757              17.02            48.0  
23758              17.02            48.0  

[22800 rows x 8 columns]

In [24]:
df.to_csv("iphone.csv", index=True, encoding="utf-8-sig")

sklearn

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [4]:
df = pd.read_csv("iphone.csv")

In [5]:
df = df.drop(columns=["Unnamed: 0", "Unnamed: 0.1","Review Text"], errors="ignore")

In [6]:
df

Product Name     Price  Rating  \
0             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
1             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
2             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
3             Apple iPhone 15 (Blue, 128 GB)   64900.0     4.0   
4             Apple iPhone 15 (Blue, 128 GB)   64900.0     5.0   
...                                      ...       ...     ...   
22795  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     3.0   
22796  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
22797  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
22798  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   
22799  Apple iPhone 15 Plus (Yellow, 512 GB)  104900.0     5.0   

                Review Title  ROM_GB  Display_Size_inch  Main_Camera_MP  
0          Worth every penny   128.0              15.49            48.0  
1                  Just wow!   128.0              15.49            48.0  
2      Mind-blowing purchase   128.0              15.49            48.0  
3                Good choice   128.0              15.49            48.0  
4                  Just wow!   128.0              15.49            48.0  
...                      ...     ...                ...             ...  
22795                   Nice   512.0              17.02            48.0  
22796                Awesome   512.0              17.02            48.0  
22797                Awesome   512.0              17.02            48.0  
22798              Fabulous!   512.0              17.02            48.0  
22799              Fabulous!   512.0              17.02            48.0  

[22800 rows x 7 columns]

In [7]:
y = df["Rating"].astype(int)
X = df.drop(columns=["Rating"])

In [8]:
text_features = ["Review Title"]
numeric_features = ["Price", "ROM_GB", "Display_Size_inch", "Main_Camera_MP"]
categorical_features = ["Product Name"]

In [9]:
preprocessor = ColumnTransformer([
    ("text", TfidfVectorizer(stop_words=None), "Review Title"),  # you can add more text columns if needed
    ("num", StandardScaler(), numeric_features),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
])

In [13]:
pipeline1 = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(n_estimators=100, random_state=42))
])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [15]:
pipeline1.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('text', TfidfVectorizer(),
                                                  'Review Title'),
                                                 ('num', StandardScaler(),
                                                  ['Price', 'ROM_GB',
                                                   'Display_Size_inch',
                                                   'Main_Camera_MP']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Product Name'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [16]:
y_pred = pipeline1.predict(X_test)

In [17]:
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("📋 Classification Report:\n", classification_report(y_test, y_pred))

✅ Accuracy: 0.9767543859649123
📊 Confusion Matrix:
 [[  89    4    7]
 [   2  340   73]
 [   7   13 4025]]
📋 Classification Report:
               precision    recall  f1-score   support

           3       0.91      0.89      0.90       100
           4       0.95      0.82      0.88       415
           5       0.98      1.00      0.99      4045

    accuracy                           0.98      4560
   macro avg       0.95      0.90      0.92      4560
weighted avg       0.98      0.98      0.98      4560



In [44]:
new_data = pd.DataFrame({
    "Product Name": ["Apple iPhone 15 (Blue, 128 GB)"],
    "Price": [64900.0],  # You can include or exclude this if not used
    "Review Title": ["poor product"],
    "ROM_GB": [128.0],
    "Display_Size_inch": [15.49],
    "Main_Camera_MP": [48.0]
})

prediction = pipeline1.predict(new_data)
print(" Predicted Rating:", prediction[0])


 Predicted Rating: 5


In [22]:
df['Rating'].value_counts()

Rating
5.0    20223
4.0     2076
3.0      501
Name: count, dtype: int64

In [23]:
df1=pd.read_csv('final.csv')
df1

Rating                  Title
0          5      Worth every penny
1          5              Just wow!
2          5  Mind-blowing purchase
3          5                Awesome
4          5              Just wow!
...      ...                    ...
1775       4            Really Nice
1776       4             Delightful
1777       4           Nice product
1778       4              Very Good
1779       4            Good choice

[1780 rows x 2 columns]

In [24]:
df1.isnull().any()

Rating    False
Title     False
dtype: bool

In [43]:
df1['Rating'].value_counts().sort_index()

Rating
1    369
2    127
3    345
4     49
5    890
Name: count, dtype: int64

In [26]:
X = df1['Title']
y = df1['Rating']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y)

In [28]:
pipeline2 = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words=None)),
    ('clf', RandomForestClassifier(n_estimators=100, random_state=42))
])

pipeline2.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier(random_state=42))])

In [29]:
y_pred = pipeline2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9803370786516854
Confusion Matrix:
 [[ 71   0   2   0   1]
 [  1  23   1   0   0]
 [  0   0  68   1   0]
 [  0   0   0   9   1]
 [  0   0   0   0 178]]
Classification Report:
               precision    recall  f1-score   support

           1       0.99      0.96      0.97        74
           2       1.00      0.92      0.96        25
           3       0.96      0.99      0.97        69
           4       0.90      0.90      0.90        10
           5       0.99      1.00      0.99       178

    accuracy                           0.98       356
   macro avg       0.97      0.95      0.96       356
weighted avg       0.98      0.98      0.98       356



In [39]:
sample_review = [" amazing product"]
predicted_rating = pipeline2.predict(sample_review)
print(f"Predicted Rating: {predicted_rating[0]}")


Predicted Rating: 4
